version: '1'
services:
  express-app:
    build: .
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment: # Set environment variables for the Express app container
      - MONGO_URI=mongodb://mongodb:27017/my_database
    volumes:
      - .:/usr/src/app
    command: npm run serve:dev


  mongodb:
    image: mongo
    ports:
      - "27017:27017"
